#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd "$(git rev-parse --show-toplevel)/backend"
echo "Running lint check..."
npm run lint
if [ $? -ne 0 ]; then
  echo "ESLint failed. Fix errors before pushing."
  exit 1
fi
echo "Running prettier check..."
npm run prettier
if [ $? -ne 0 ]; then
  echo "Prettier check failed. Run 'npm run prettier:fix' before pushing."
  exit 1
fi
echo "All checks passed."
